### ISSUE TITLE
Examples in README

### ISSUE THREAD

**Issue by onlywei** [athaeryn/farfetched#7]
I think it will help a lot to include some basic examples of how to mock using this library in the README.

**Comment by athaeryn** [comment]
I agree. What kind of examples would you find most helpful?

**Comment by onlywei** [comment]
Can we just start with the basic mock? If I call `fetch('/foo')`, how would I send a fake response to it?

**Comment by athaeryn** [comment]
How about something like this?

``` js
// Call this once to enable farfetched.
farfetched.attach(window)

//
// A basic mocked response
//
farfetched('/the-answer', { response: '42' })

fetch('/the-answer')
  .then(log) // '42'


//
// Dynamic responses
//
farfetched(/\/food/, { response: (url) => url.split('?')[1] })

fetch('/food?apples')
  .then(log) // 'apples'


// Helper logging function.
function log (response) {
  response.text().then(console.log.bind(console))
}
```

**Comment by dariocravero** [comment]
I like how small this library is :). I might suggest some changes to the internals later on. As of the examples, it's a great idea to show how to use it on the README and that example would do just fine :)

Here's a little helper we're using to make the tests more concise:

``` js
// mock-fetch.js
import farfetched from 'farfetched';

export default function mockFetch(uri, response) {
  farfetched.attach(global);

  const id = farfetched(uri, {
    response
  });

  return function mockFetchCleanup() {
    farfetched.clear(id);
    farfetched.restore(global);
  }
}
```

Then on your test:

``` js
import mockFetch from './mock-fetch';
import test from 'tape';

test('#save', t => {
  const restoreFetch = mockFetch('/path/to/stuff', {ok: true});

  fetch('/path/to/stuff').then(response => {
    t.deepEquals(response, {ok: true}, 'gets response');

    restoreFetch();
    t.end();
  });
});
```

Could that helper be part of the bundle? Or should it be a library on its own?

**Comment by athaeryn** [comment]
Thanks, I'd love feedback and suggestions!

I don't think the test helper belongs in the farfetched package, but if you make a library I'll link to it from the readme.

**Comment by dariocravero** [comment]
Great, I'll throw that into its own little library and submit a PR on the readme then!
